config/routes.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.



Diaspora::Application.routes.draw do
  resources :people, :only => [:index, :show, :destroy]
  resources :users, :except => [:create, :new]
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments, :except => [:index]
  resources :requests, :except => [:edit, :update]
  resources :photos, :except => [:index]
  resources :albums

  match 'aspects/manage', :to => 'aspects#manage'
  resources :aspects, :except => [:edit]
  match 'aspects/move_friends', :to => 'aspects#move_friends', :as => 'move_friends'
  match 'aspects/move_friend', :to => 'aspects#move_friend', :as => 'move_friend'

  match 'warzombie',          :to => "dev_utilities#warzombie"
  match 'zombiefriends',      :to => "dev_utilities#zombiefriends"
  match 'zombiefriendaccept', :to => "dev_utilities#zombiefriendaccept"
  match 'set_backer_number', :to => "dev_utilities#set_backer_number"
  match 'set_profile_photo', :to => "dev_utilities#set_profile_photo"

  #routes for devise, not really sure you will need to mess with this in the future, lets put default,
  #non mutable stuff in anohter file
  devise_for :users, :controllers => {:registrations => "registrations"}
  match 'login',  :to => 'devise/sessions#new',      :as => "new_user_session"
  match 'logout', :to => 'devise/sessions#destroy',  :as => "destroy_user_session"
  match 'get_to_the_choppa', :to => 'registrations#new', :as => "new_user_registration"

  #public routes
  #
  match 'webfinger', :to => 'publics#webfinger'
  match 'hcard/users/:id',    :to => 'publics#hcard'

  match '.well-known/host-meta',:to => 'publics#host_meta'        
  match 'receive/users/:id',     :to => 'publics#receive'    
  match 'log', :to => "dev_utilities#log"

  #root
  root :to => 'aspects#index'
end

app/models/person.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


require 'lib/hcard'

class Person
  include MongoMapper::Document
  include ROXML
  include Encryptor::Public

  xml_accessor :_id
  xml_accessor :diaspora_handle
  xml_accessor :url
  xml_accessor :profile, :as => Profile
  xml_reader :exported_key
  
  key :url,            String
  key :diaspora_handle, String, :unique => true
  key :serialized_key, String 

  key :owner_id,  ObjectId

  one :profile, :class_name => 'Profile'
  many :albums, :class_name => 'Album', :foreign_key => :person_id
  belongs_to :owner, :class_name => 'User'

  timestamps!

  before_destroy :remove_all_traces
  before_validation :clean_url
  validates_presence_of :url, :profile, :serialized_key 
  validates_format_of :url, :with =>
     /^(https?):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*(\.[a-z]{2,5})?(:[0-9]{1,5})?(\/.*)?$/ix
  
  
  def self.search(query)
    Person.all('$where' => "function() { return this.diaspora_handle.match(/^#{query}/i) ||
               this.profile.first_name.match(/^#{query}/i) ||
               this.profile.last_name.match(/^#{query}/i); }")
  end

  def real_name
    "#{profile.first_name.to_s} #{profile.last_name.to_s}"
  end
  def owns?(post)
    self.id == post.person.id
  end

  def receive_url
    "#{self.url}receive/users/#{self.id}/"
  end

  def encryption_key
    OpenSSL::PKey::RSA.new( serialized_key )
  end

  def encryption_key= new_key
    raise TypeError unless new_key.class == OpenSSL::PKey::RSA
    serialized_key = new_key.export
  end

  def public_key_hash
    Base64.encode64 OpenSSL::Digest::SHA256.new(self.exported_key).to_s
  end

  def public_key
    encryption_key.public_key
  end

  def exported_key
    encryption_key.public_key.export
  end

  def exported_key= new_key
    raise "Don't change a key" if serialized_key
    @serialized_key = new_key
  end

  def self.by_webfinger( identifier )
    local_person = Person.first(:diaspora_handle => identifier.gsub('acct:', ''))
    
     if local_person
       local_person
     elsif  !identifier.include?("localhost")
       begin
        f = Redfinger.finger(identifier)
       rescue SocketError => e
         raise "Diaspora server for #{identifier} not found" if e.message =~ /Name or service not known/
       end
       raise "No webfinger profile found at #{identifier}" unless f
       Person.from_webfinger_profile(identifier, f )
     end
  end

  def self.from_webfinger_profile( identifier, profile)
    new_person = Person.new

    public_key = profile.links.select{|x| x.rel == 'diaspora-public-key'}.first.href
    new_person.exported_key = Base64.decode64 public_key

    guid = profile.links.select{|x| x.rel == 'http://joindiaspora.com/guid'}.first.href
    new_person.id = guid
    
    new_person.diaspora_handle = identifier
    
    hcard = HCard.find profile.hcard.first[:href]

    new_person.url = hcard[:url]
    new_person.profile = Profile.new(:first_name => hcard[:given_name], :last_name => hcard[:family_name])
    if new_person.save
      new_person
    else
      nil
    end
  end
  
  def remote?
    owner.nil?
  end

  def as_json(opts={})
    {
      :person => {
        :id           => self.id,
        :name         => self.real_name,
        :diaspora_handle        => self.diaspora_handle,
        :url          => self.url,
        :exported_key => exported_key
      }
    }
  end

  protected
  def clean_url
    self.url ||= "http://localhost:3000/" if self.class == User
    if self.url
      self.url = 'http://' + self.url unless self.url.match('http://' || 'https://')
      self.url = self.url + '/' if self.url[-1,1] != '/'
    end
  end

  private
  def remove_all_traces
    Post.all(:person_id => id).each{|p| p.delete}
    Album.all(:person_id => id).each{|p| p.delete}
  end
end

app/controllers/people_controller.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


class PeopleController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => [:index, :show]
  
  def index
    @aspects_dropdown_array = current_user.aspects.collect{|x| [x.to_s, x.id]} 
    @people = Person.search params[:q]
    respond_with @people
  end
  
  def show
    @person = current_user.visible_person_by_id(params[:id])
    @profile = @person.profile
    @aspects_with_person = current_user.aspects_with_person(@person)
    @aspects_dropdown_array = current_user.aspects.collect{|x| [x.to_s, x.id]} 
    @posts = current_user.visible_posts_from_others(:from => @person).paginate :page => params[:page], :order => 'created_at DESC'
    @latest_status_message = current_user.raw_visible_posts.find_all_by__type_and_person_id("StatusMessage", params[:id]).last
    @post_count = @posts.count
    respond_with @person
  end
  
  def destroy
    current_user.unfriend(current_user.visible_person_by_id(params[:id]))
    respond_with :location => root_url
  end
  
end

app/helpers/people_helper.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


module PeopleHelper
  
  def search_or_index
    if params[:q]
      " results for #{params[:q]}"
    else
      " people on pod is aware of"
    end
    
  end
end

app/views/people/index.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- content_for :publish do
  %h1
    Search

  =form_tag '/people', :method => "get" do
    = text_field_tag :q
    = submit_tag "search"

- content_for :left_pane do
  \.

= (@people.count).to_s + search_or_index
%table
  %tr
    %th real name
    %th diaspora handle
    %th url
    - for person in @people
      %tr
        - if current_user.friends.include? person
          %td= link_to person.real_name, person
        - else
          %td= person.real_name

        %td= person.diaspora_handle
        %td= person.url
        
        -if current_user.friends.include? person

        - elsif person.id == current_user.person.id
          %td
          %td that's you!
        -elsif current_user.pending_requests.find_by_person_id(person.id)
          %td 
          %td ^-you have a friend request from this person       
        -elsif current_user.pending_requests.find_by_url(person.receive_url)
          %td 
          %td friend request pending
        -else
          %td
          %td
            = form_for Request.new do |f|
              = f.select(:aspect_id, @aspects_dropdown_array)
              = f.hidden_field :destination_url, :value => person.diaspora_handle
              = f.submit "add friend"

app/views/people/new.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- title "New Person"

= form_for @person do |f|
  = f.error_messages
  %p
    = f.label :diaspora_handle
    %br
    = f.text_field :diaspora_handle
  %p
    = f.label :url
    %br
    = f.text_field :url
    
    =f.fields_for :profile do |p|
      %p
        = p.label :first_name
        %br
        = p.text_field :first_name
        
      %p
        = p.label :last_name
        %br
        = p.text_field :last_name
    = f.submit


%p= link_to "Back to List", people_path

app/views/people/show.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- content_for :page_title do
  = @person.real_name

- content_for :left_pane do
  #profile
    .profile_photo
      = person_image_link(@person)
    %ul
      -unless @posts.first.nil?
        %li
          %i= "last seen: #{how_long_ago(@posts.first)}"
      - if @person != current_user.person && current_user.friends.include?(@person)
        %li
          %i= "friends since: #{how_long_ago(@person)}"
        %li
          = form_tag move_friend_path
          = select :to, :to,  @aspects_dropdown_array, :selected => @aspects_with_person.first.id
          = hidden_field_tag :from, :from, :value => @aspects_with_person.first.id
          = hidden_field_tag :friend_id, :friend_id, :value => @person.id
          = submit_tag "save"

    - if @person != current_user.person && current_user.friends.include?(@person)
      = link_to 'remove friend', @person, :confirm => 'Are you sure?', :method => :delete, :class => "button"

.span-20.last
  
  .span-19.last
    - if @posts
      %ul#stream
        - for post in @posts
          = render type_partial(post), :post => post unless post.class == Album
        = will_paginate @posts
    - else
      %h3 no posts to display!