config/routes.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.



Diaspora::Application.routes.draw do
  resources :people, :only => [:index, :show, :destroy]
  resources :users, :except => [:create, :new]
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments, :except => [:index]
  resources :requests, :except => [:edit, :update]
  resources :photos, :except => [:index]
  resources :albums

  match 'aspects/manage', :to => 'aspects#manage'
  resources :aspects, :except => [:edit]
  match 'aspects/move_friends', :to => 'aspects#move_friends', :as => 'move_friends'
  match 'aspects/move_friend', :to => 'aspects#move_friend', :as => 'move_friend'

  match 'warzombie',          :to => "dev_utilities#warzombie"
  match 'zombiefriends',      :to => "dev_utilities#zombiefriends"
  match 'zombiefriendaccept', :to => "dev_utilities#zombiefriendaccept"
  match 'set_backer_number', :to => "dev_utilities#set_backer_number"
  match 'set_profile_photo', :to => "dev_utilities#set_profile_photo"

  #routes for devise, not really sure you will need to mess with this in the future, lets put default,
  #non mutable stuff in anohter file
  devise_for :users, :controllers => {:registrations => "registrations"}
  match 'login',  :to => 'devise/sessions#new',      :as => "new_user_session"
  match 'logout', :to => 'devise/sessions#destroy',  :as => "destroy_user_session"
  match 'get_to_the_choppa', :to => 'registrations#new', :as => "new_user_registration"

  #public routes
  #
  match 'webfinger', :to => 'publics#webfinger'
  match 'hcard/users/:id',    :to => 'publics#hcard'

  match '.well-known/host-meta',:to => 'publics#host_meta'        
  match 'receive/users/:id',     :to => 'publics#receive'    
  match 'log', :to => "dev_utilities#log"

  #root
  root :to => 'aspects#index'
end

app/views/shared/_aspect_friends.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


#friend_pictures
  = owner_image_link
  - for friend in @friends
    = person_image_link(friend)

  -unless @aspect == :all
    = link_to (image_tag('add_friend_button.png', :height => "50px", :width => "50px")), "#add_request_pane", :id => 'add_request_button'
  
    .yo{:style => 'display:none'}
      #add_request_pane
        = render "requests/new_request", :aspect => @aspect 
  -else
    .clear
      = link_to "add friends", aspects_manage_path 

app/views/shared/_aspect_nav.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


#aspect_nav
  %ul
    - for aspect in @aspects
      %li{:id => aspect.id, :class => ("selected" if current_aspect?(aspect))}
        = link_for_aspect aspect

  %ul{ :style => "position:absolute;right:0;bottom:0.01em;"}
    %li{:class => ("selected" if @aspect == :all)}
      = link_to "All Aspects", root_url

    %li{ :style => "margin-right:0;", :class => ("selected" if @aspect == :manage)}
      = link_to ( (@request_count == 0)? "manage" : "manage (#{@request_count})"), {:controller => :aspects, :action => :manage}, :class => "edit_aspect_button", :class => new_request(@request_count), :title => "Manage your Aspects"

  .yo{ :style => "display:none;"}
    #add_aspect_pane
      = render "aspects/new_aspect"

app/views/shared/_post_wrapper.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


%li.message{:id => post.id, :class => ("mine" if current_user.owns?(post))}
  = person_image_link(post.person)
  = yield post_yield_tag(post)
  = = render type_partial(post), :post => post

app/views/shared/_publisher.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


#publisher
  = owner_image_tag

  = form_for StatusMessage.new, :remote => true do |f|
    = f.error_messages
    %p
      %label{:for => "status_message_message"} Message
      = f.text_area :message, :rows => 2

    %ul.aspect_selector{ :style => "display:none;"}
      going to...
      - for aspect in @aspects
        %li
          = check_box_tag("aspect_ids[]", aspect.id, @aspect == :all || current_aspect?(aspect) )
          = aspect.name
      
    = f.submit "Share"

app/views/shared/_sub_header.haml
#aspect_header
  .container
    .span-5.last
      - if @person
        %h1
          = @person.real_name
      - else
        %h1
          - if @aspect == :all
            = link_to "All Aspects", root_path
          - elsif @aspect == :manage
            = link_to "Manage Aspects", root_path
          - else
            = link_to @aspect.name, @aspect

      .page_title
        = yield :page_title

    .span-19.last{ :style => "position:relative;" }
      = yield :publish

app/views/shared/log.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


= @log.to_s