config/routes.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.



Diaspora::Application.routes.draw do
  resources :people, :only => [:index, :show, :destroy]
  resources :users, :except => [:create, :new]
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments, :except => [:index]
  resources :requests, :except => [:edit, :update]
  resources :photos, :except => [:index]
  resources :albums

  match 'aspects/manage', :to => 'aspects#manage'
  resources :aspects, :except => [:edit]
  match 'aspects/move_friends', :to => 'aspects#move_friends', :as => 'move_friends'
  match 'aspects/move_friend', :to => 'aspects#move_friend', :as => 'move_friend'

  match 'warzombie',          :to => "dev_utilities#warzombie"
  match 'zombiefriends',      :to => "dev_utilities#zombiefriends"
  match 'zombiefriendaccept', :to => "dev_utilities#zombiefriendaccept"
  match 'set_backer_number', :to => "dev_utilities#set_backer_number"
  match 'set_profile_photo', :to => "dev_utilities#set_profile_photo"

  #routes for devise, not really sure you will need to mess with this in the future, lets put default,
  #non mutable stuff in anohter file
  devise_for :users, :controllers => {:registrations => "registrations"}
  match 'login',  :to => 'devise/sessions#new',      :as => "new_user_session"
  match 'logout', :to => 'devise/sessions#destroy',  :as => "destroy_user_session"
  match 'get_to_the_choppa', :to => 'registrations#new', :as => "new_user_registration"

  #public routes
  #
  match 'webfinger', :to => 'publics#webfinger'
  match 'hcard/users/:id',    :to => 'publics#hcard'

  match '.well-known/host-meta',:to => 'publics#host_meta'        
  match 'receive/users/:id',     :to => 'publics#receive'    
  match 'log', :to => "dev_utilities#log"

  #root
  root :to => 'aspects#index'
end

app/models/status_message.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


class StatusMessage < Post
  
  xml_name :status_message
  xml_accessor :message

  key :message, String
  validates_presence_of :message
  
  
  def to_activity
        <<-XML
  <entry>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <title>#{self.message}</title>
  <link rel="alternate" type="text/html" href="#{person.url}status_messages/#{self.id}"/>
  <id>#{person.url}status_messages/#{self.id}</id>
  <published>#{self.created_at.xmlschema}</published>
  <updated>#{self.updated_at.xmlschema}</updated>
  </entry>
        XML
  end
  
  def latest_hash
    { :text => message}
  end
end

app/controllers/status_messages_controller.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


class StatusMessagesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => :show

  def create
    params[:status_message][:to] = params[:aspect_ids]
    @status_message = current_user.post(:status_message, params[:status_message])
    respond_with @status_message
  end
  
  def destroy
    @status_message = StatusMessage.find_by_id params[:id]
    @status_message.destroy
    respond_with :location => root_url
  end
  
  def show
    @status_message = StatusMessage.find_by_id params[:id]
    respond_with @status_message
  end
end

app/helpers/status_messages_helper.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


module StatusMessagesHelper
  def my_latest_message
    unless @latest_status_message.nil?
      return @latest_status_message.message
    else
      return "No message to display."
    end
  end
end

app/views/status_messages/_new_status_message.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


= form_for StatusMessage.new, :remote => true do |f|
  = f.error_messages
  %p
    = f.text_field :message, :value => "tell me something good"
    = f.submit 'oh yeah!', :class => 'button'

app/views/status_messages/_status_message.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


%li.message{:id => post.id, :class => ("mine" if current_user.owns?(post))}

  = person_image_link(post.person)

  .content
    %span.from
      = link_to post.person.real_name, post.person 
      = auto_link sanitize post.message
      
    .info
      = link_to(how_long_ago(post), object_path(post))
      \--
      = link_to "show comments (#{post.comments.count})", '#', :class => "show_post_comments"

    = render   "comments/comments", :post => post 


  - if current_user.owns?(post)
    .destroy_link
      = link_to 'Delete', status_message_path(post), :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => "delete"

app/views/status_messages/index.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


%h1.big_text status messages
= render "status_messages/new_status_message", :status_message => @status_message
%ul#stream
  
  - for status_message in @status_messages
    = render "status_message", :post => status_message
#pagination
  = will_paginate @status_messages

app/views/status_messages/show.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- title "Status Message"

%p
  %strong Message:
  = @status_message.message
  
%p
  %strong Owner:
  = @status_message.person.real_name

%h4= "comments (#{@status_message.comments.count})"
= render "comments/comments", :post => @status_message

%p
  = link_to "Destroy", @status_message, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", status_messages_path