config/routes.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.



Diaspora::Application.routes.draw do
  resources :people, :only => [:index, :show, :destroy]
  resources :users, :except => [:create, :new]
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments, :except => [:index]
  resources :requests, :except => [:edit, :update]
  resources :photos, :except => [:index]
  resources :albums

  match 'aspects/manage', :to => 'aspects#manage'
  resources :aspects, :except => [:edit]
  match 'aspects/move_friends', :to => 'aspects#move_friends', :as => 'move_friends'
  match 'aspects/move_friend', :to => 'aspects#move_friend', :as => 'move_friend'

  match 'warzombie',          :to => "dev_utilities#warzombie"
  match 'zombiefriends',      :to => "dev_utilities#zombiefriends"
  match 'zombiefriendaccept', :to => "dev_utilities#zombiefriendaccept"
  match 'set_backer_number', :to => "dev_utilities#set_backer_number"
  match 'set_profile_photo', :to => "dev_utilities#set_profile_photo"

  #routes for devise, not really sure you will need to mess with this in the future, lets put default,
  #non mutable stuff in anohter file
  devise_for :users, :controllers => {:registrations => "registrations"}
  match 'login',  :to => 'devise/sessions#new',      :as => "new_user_session"
  match 'logout', :to => 'devise/sessions#destroy',  :as => "destroy_user_session"
  match 'get_to_the_choppa', :to => 'registrations#new', :as => "new_user_registration"

  #public routes
  #
  match 'webfinger', :to => 'publics#webfinger'
  match 'hcard/users/:id',    :to => 'publics#hcard'

  match '.well-known/host-meta',:to => 'publics#host_meta'        
  match 'receive/users/:id',     :to => 'publics#receive'    
  match 'log', :to => "dev_utilities#log"

  #root
  root :to => 'aspects#index'
end

app/models/aspect.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


class Aspect
  include MongoMapper::Document
  
  key :name,        String
  key :person_ids,  Array
  key :request_ids, Array
  key :post_ids,    Array

  many :people,   :in => :person_ids,  :class_name => 'Person'
  many :requests, :in => :request_ids, :class_name => 'Request'
  many :posts,    :in => :post_ids,    :class_name => 'Post'

  belongs_to :user, :class_name => 'User'

  validates_presence_of :name

  timestamps!
  
  def to_s
    name
  end
  
  def posts_by_person_id( id )
    id = id.to_id
    posts.detect{|x| x.person.id == id }
  end

  def as_json(opts = {})
    {
      :aspect => {
        :name   => self.name,
        :people => self.people.each{|person| person.as_json},
        :posts  => self.posts.each {|post|   post.as_json  },
      }
    }
  end
end

app/controllers/aspects_controller.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


class AspectsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => :show

  def index
    @posts = current_user.visible_posts(:by_members_of => :all).paginate :page => params[:page], :per_page => 15, :order => 'created_at DESC'
    @aspect = :all
  end

  def create
    @aspect = current_user.aspect params[:aspect]
    flash[:notice] = "Click on the plus on the left side to tell Diaspora who can see your new aspect."
    respond_with :location => aspects_manage_path
  end
  
  def new
    @aspect = Aspect.new
  end
  
  def destroy
    @aspect = Aspect.find_by_id params[:id]
    @aspect.destroy
    flash[:notice] = "You are no longer sharing the aspect called #{@aspect.name}."
    respond_with :location => aspects_url
  end
  
  def show
    @aspect   = Aspect.find_by_id params[:id]
    @friends = @aspect.people
    @posts   = current_user.visible_posts( :by_members_of => @aspect ).paginate :per_page => 15, :order => 'created_at DESC'

    respond_with @aspect
  end

  def manage
    @aspect = :manage
    @remote_requests = Request.for_user current_user
  end

  def update
    @aspect = Aspect.find_by_id(params[:id])
    @aspect.update_attributes(params[:aspect])
    flash[:notice] = "Your aspect, #{@aspect.name}, has been successfully edited."
    respond_with @aspect
  end

  def move_friends
    params[:moves].each{ |move|
      move = move[1]
      unless current_user.move_friend(move)
        flash[:error] = "Aspect editing failed for friend #{Person.find_by_id( move[:friend_id] ).real_name}."
        redirect_to Aspect.first, :action => "edit"
        return
      end
    }

    flash[:notice] = "Aspects edited successfully."
    redirect_to Aspect.first, :action => "edit"
  end

  def move_friend
    unless current_user.move_friend( :friend_id => params[:friend_id], :from => params[:from], :to => params[:to][:to]) 
      flash[:error] = "didn't work #{params.inspect}"
    end
    if aspect = Aspect.first(:id => params[:to][:to])
      flash[:notice] = "You are now showing your friend a different aspect of yourself."
      respond_with aspect
    else
      flash[:notice] = "You are now showing your friend a different aspect of yourself."
      respond_with Person.first(:id => params[:friend_id])
    end
  end
end

app/helpers/aspects_helper.rb
#   Copyright (c) 2010, Disapora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


module AspectsHelper
  def link_for_aspect( aspect )
    link_to aspect.name, aspect
  end
end

app/views/aspects/_new_aspect.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


%h1 Add a new aspect
= form_for Aspect.new do |f|
  = f.error_messages
  %p
    = f.label :name
    = f.text_field :name
    = f.submit 'create', :class => 'button'

app/views/aspects/index.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- content_for :page_title do
  = link_to "photos", albums_path(:aspect => @aspect)
  

- content_for :left_pane do
  = render "shared/aspect_friends"

- content_for :publish do
  = render "shared/publisher", :aspect_ids => :all

%ul#stream
  - for post in @posts
    = render type_partial(post), :post => post unless post.class == Album
#pagination
  = will_paginate @posts

app/views/aspects/manage.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- content_for :head do 
  = javascript_include_tag 'jquery-ui-1.8.4.custom.min.js'
  = javascript_include_tag 'aspect-edit.js'

- content_for :left_pane do
  %h1
    Requests

  .requests
    %ul
      - for request in @remote_requests
        %li.requested_person{:id => request.person.id, :request_id => request.id}
          = person_image_tag(request.person)
          .name
            = request.person.real_name
  %h1
    Ignore/Remove

  %li.remove
    %ul

- content_for :publish do
  = link_to("add a new aspect", "#add_aspect_pane", :id => "add_aspect_button", :class => "new_aspect button", :title => "Add a new aspect")



%ul#aspect_list
  - for aspect in @aspects
    %li.aspect
      
      .aspect_name
        %h1{:contenteditable => true}= aspect.name

        .tools
          = link_to "add a new friend", "#add_request_pane_#{aspect.id}", :class => 'add_request_button'
          |
          = link_to "show", aspect_path(aspect)
      
      %ul{:id => aspect.id}
      
        -if aspect.people.size < 1
          %li.grey Drag to add people

        -else
          -for person in aspect.people

            %li.person{:id => person.id, :from_aspect_id => aspect.id}
              = person_image_tag(person)
              .name
                = person.real_name
        .yo{:style => 'display:none'}
          %div{:id => "add_request_pane_#{aspect.id}"}
            = render "requests/new_request", :aspect => aspect

%p
  %br
  = link_to 'Update Aspects', '#', :class => 'button', :id => "move_friends_link"

#content_bottom

app/views/aspects/show.html.haml
-#   Copyright (c) 2010, Disapora Inc.  This file is
-#   licensed under the Affero General Public License version 3.  See
-#   the COPYRIGHT file.


- content_for :page_title do
  = link_to "photos", albums_path(:aspect => @aspect)

- content_for :left_pane do
  = render "shared/aspect_friends"

- content_for :publish do
  = render "shared/publisher", :aspect_ids => :all

%ul#stream
  - for post in @posts
    = render type_partial(post), :post => post unless post.class == Album
#pagination
  = will_paginate @posts